/**
 * @fileoverview gRPC-Web generated client stub for chart_data
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: chart.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.chart_data = require('./chart_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chart_data.ChartServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.chart_data.ChartServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chart_data.VN30PSRequest,
 *   !proto.chart_data.VN30PSResponse>}
 */
const methodDescriptor_ChartService_VN30PS = new grpc.web.MethodDescriptor(
  '/chart_data.ChartService/VN30PS',
  grpc.web.MethodType.UNARY,
  proto.chart_data.VN30PSRequest,
  proto.chart_data.VN30PSResponse,
  /**
   * @param {!proto.chart_data.VN30PSRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chart_data.VN30PSResponse.deserializeBinary
);


/**
 * @param {!proto.chart_data.VN30PSRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chart_data.VN30PSResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chart_data.VN30PSResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chart_data.ChartServiceClient.prototype.vN30PS =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chart_data.ChartService/VN30PS',
      request,
      metadata || {},
      methodDescriptor_ChartService_VN30PS,
      callback);
};


/**
 * @param {!proto.chart_data.VN30PSRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chart_data.VN30PSResponse>}
 *     Promise that resolves to the response
 */
proto.chart_data.ChartServicePromiseClient.prototype.vN30PS =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chart_data.ChartService/VN30PS',
      request,
      metadata || {},
      methodDescriptor_ChartService_VN30PS);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.chart_data.FBFSRequest,
 *   !proto.chart_data.FBFSResponse>}
 */
const methodDescriptor_ChartService_FBFS = new grpc.web.MethodDescriptor(
  '/chart_data.ChartService/FBFS',
  grpc.web.MethodType.UNARY,
  proto.chart_data.FBFSRequest,
  proto.chart_data.FBFSResponse,
  /**
   * @param {!proto.chart_data.FBFSRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.chart_data.FBFSResponse.deserializeBinary
);


/**
 * @param {!proto.chart_data.FBFSRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.chart_data.FBFSResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.chart_data.FBFSResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.chart_data.ChartServiceClient.prototype.fBFS =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/chart_data.ChartService/FBFS',
      request,
      metadata || {},
      methodDescriptor_ChartService_FBFS,
      callback);
};


/**
 * @param {!proto.chart_data.FBFSRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.chart_data.FBFSResponse>}
 *     Promise that resolves to the response
 */
proto.chart_data.ChartServicePromiseClient.prototype.fBFS =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/chart_data.ChartService/FBFS',
      request,
      metadata || {},
      methodDescriptor_ChartService_FBFS);
};


module.exports = proto.chart_data;

