/**
 * @fileoverview gRPC-Web generated client stub for columns_definition
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: columns_definition.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.columns_definition = require('./columns_definition_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.columns_definition.ColumnsDefinitionServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.columns_definition.ColumnsDefinitionServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.columns_definition.CreateColumnsDefinitionRequest,
 *   !proto.columns_definition.CreateColumnsDefinitionResponse>}
 */
const methodDescriptor_ColumnsDefinitionService_CreateColumnsDefinition = new grpc.web.MethodDescriptor(
  '/columns_definition.ColumnsDefinitionService/CreateColumnsDefinition',
  grpc.web.MethodType.UNARY,
  proto.columns_definition.CreateColumnsDefinitionRequest,
  proto.columns_definition.CreateColumnsDefinitionResponse,
  /**
   * @param {!proto.columns_definition.CreateColumnsDefinitionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.columns_definition.CreateColumnsDefinitionResponse.deserializeBinary
);


/**
 * @param {!proto.columns_definition.CreateColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.columns_definition.CreateColumnsDefinitionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.columns_definition.CreateColumnsDefinitionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.columns_definition.ColumnsDefinitionServiceClient.prototype.createColumnsDefinition =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/CreateColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_CreateColumnsDefinition,
      callback);
};


/**
 * @param {!proto.columns_definition.CreateColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.columns_definition.CreateColumnsDefinitionResponse>}
 *     Promise that resolves to the response
 */
proto.columns_definition.ColumnsDefinitionServicePromiseClient.prototype.createColumnsDefinition =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/CreateColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_CreateColumnsDefinition);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.columns_definition.GetColumnsDefinitionRequest,
 *   !proto.columns_definition.GetColumnsDefinitionResponse>}
 */
const methodDescriptor_ColumnsDefinitionService_GetColumnsDefinition = new grpc.web.MethodDescriptor(
  '/columns_definition.ColumnsDefinitionService/GetColumnsDefinition',
  grpc.web.MethodType.UNARY,
  proto.columns_definition.GetColumnsDefinitionRequest,
  proto.columns_definition.GetColumnsDefinitionResponse,
  /**
   * @param {!proto.columns_definition.GetColumnsDefinitionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.columns_definition.GetColumnsDefinitionResponse.deserializeBinary
);


/**
 * @param {!proto.columns_definition.GetColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.columns_definition.GetColumnsDefinitionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.columns_definition.GetColumnsDefinitionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.columns_definition.ColumnsDefinitionServiceClient.prototype.getColumnsDefinition =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/GetColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_GetColumnsDefinition,
      callback);
};


/**
 * @param {!proto.columns_definition.GetColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.columns_definition.GetColumnsDefinitionResponse>}
 *     Promise that resolves to the response
 */
proto.columns_definition.ColumnsDefinitionServicePromiseClient.prototype.getColumnsDefinition =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/GetColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_GetColumnsDefinition);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.columns_definition.UpdateColumnsDefinitionRequest,
 *   !proto.columns_definition.UpdateColumnsDefinitionResponse>}
 */
const methodDescriptor_ColumnsDefinitionService_UpdateColumnsDefinition = new grpc.web.MethodDescriptor(
  '/columns_definition.ColumnsDefinitionService/UpdateColumnsDefinition',
  grpc.web.MethodType.UNARY,
  proto.columns_definition.UpdateColumnsDefinitionRequest,
  proto.columns_definition.UpdateColumnsDefinitionResponse,
  /**
   * @param {!proto.columns_definition.UpdateColumnsDefinitionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.columns_definition.UpdateColumnsDefinitionResponse.deserializeBinary
);


/**
 * @param {!proto.columns_definition.UpdateColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.columns_definition.UpdateColumnsDefinitionResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.columns_definition.UpdateColumnsDefinitionResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.columns_definition.ColumnsDefinitionServiceClient.prototype.updateColumnsDefinition =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/UpdateColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_UpdateColumnsDefinition,
      callback);
};


/**
 * @param {!proto.columns_definition.UpdateColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.columns_definition.UpdateColumnsDefinitionResponse>}
 *     Promise that resolves to the response
 */
proto.columns_definition.ColumnsDefinitionServicePromiseClient.prototype.updateColumnsDefinition =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/UpdateColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_UpdateColumnsDefinition);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.columns_definition.DeleteColumnsDefinitionRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ColumnsDefinitionService_DeleteColumnsDefinition = new grpc.web.MethodDescriptor(
  '/columns_definition.ColumnsDefinitionService/DeleteColumnsDefinition',
  grpc.web.MethodType.UNARY,
  proto.columns_definition.DeleteColumnsDefinitionRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.columns_definition.DeleteColumnsDefinitionRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.columns_definition.DeleteColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.columns_definition.ColumnsDefinitionServiceClient.prototype.deleteColumnsDefinition =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/DeleteColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_DeleteColumnsDefinition,
      callback);
};


/**
 * @param {!proto.columns_definition.DeleteColumnsDefinitionRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.columns_definition.ColumnsDefinitionServicePromiseClient.prototype.deleteColumnsDefinition =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/DeleteColumnsDefinition',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_DeleteColumnsDefinition);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.columns_definition.ListColumnsDefinitionsRequest,
 *   !proto.columns_definition.ListColumnsDefinitionsResponse>}
 */
const methodDescriptor_ColumnsDefinitionService_ListColumnsDefinitions = new grpc.web.MethodDescriptor(
  '/columns_definition.ColumnsDefinitionService/ListColumnsDefinitions',
  grpc.web.MethodType.UNARY,
  proto.columns_definition.ListColumnsDefinitionsRequest,
  proto.columns_definition.ListColumnsDefinitionsResponse,
  /**
   * @param {!proto.columns_definition.ListColumnsDefinitionsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.columns_definition.ListColumnsDefinitionsResponse.deserializeBinary
);


/**
 * @param {!proto.columns_definition.ListColumnsDefinitionsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.columns_definition.ListColumnsDefinitionsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.columns_definition.ListColumnsDefinitionsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.columns_definition.ColumnsDefinitionServiceClient.prototype.listColumnsDefinitions =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/ListColumnsDefinitions',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_ListColumnsDefinitions,
      callback);
};


/**
 * @param {!proto.columns_definition.ListColumnsDefinitionsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.columns_definition.ListColumnsDefinitionsResponse>}
 *     Promise that resolves to the response
 */
proto.columns_definition.ColumnsDefinitionServicePromiseClient.prototype.listColumnsDefinitions =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/columns_definition.ColumnsDefinitionService/ListColumnsDefinitions',
      request,
      metadata || {},
      methodDescriptor_ColumnsDefinitionService_ListColumnsDefinitions);
};


module.exports = proto.columns_definition;

