/**
 * @fileoverview gRPC-Web generated client stub for user
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.3
// source: user.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.user = require('./user_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.GoogleSSORequest,
 *   !proto.user.GoogleSSOResponse>}
 */
const methodDescriptor_UserService_GoogleSSO = new grpc.web.MethodDescriptor(
  '/user.UserService/GoogleSSO',
  grpc.web.MethodType.UNARY,
  proto.user.GoogleSSORequest,
  proto.user.GoogleSSOResponse,
  /**
   * @param {!proto.user.GoogleSSORequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.GoogleSSOResponse.deserializeBinary
);


/**
 * @param {!proto.user.GoogleSSORequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.GoogleSSOResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.GoogleSSOResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.UserServiceClient.prototype.googleSSO =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.UserService/GoogleSSO',
      request,
      metadata || {},
      methodDescriptor_UserService_GoogleSSO,
      callback);
};


/**
 * @param {!proto.user.GoogleSSORequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.GoogleSSOResponse>}
 *     Promise that resolves to the response
 */
proto.user.UserServicePromiseClient.prototype.googleSSO =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.UserService/GoogleSSO',
      request,
      metadata || {},
      methodDescriptor_UserService_GoogleSSO);
};


module.exports = proto.user;

